version: '2'
services:
  app:
    container_name: syspass-app
    image: syspass/syspass:3.2.8-php7.3
    restart: always
    ports:
      - "80"
      - "443"
    links:
      - db
    volumes:
      - /var/www/html/sysPass/app/config
      - /var/www/html/sysPass/app/backup
  db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    ports:
      - "3306"
    volumes:
      - /var/lib/mysql
